### ISSUE TITLE
example #1 average allocated cpu

### ISSUE THREAD

**Issue by lpichler** [ManageIQ/manageiq-consumption#52]
Hello,

I am playing with your repo and I think that it will be good to see the example on some more real cases.

Let's assume this situation:
   - Hourly rate $1 per 1CPU
   - let's take the month of 30 days
   - 1 CPU was allocated in first 10 days in a month
   - 2 CPUs were allocated in last 20 days

So calculation should looks like:
`VM as 1 CPU for 10 days and 2 CPU for 20 days then the cost should be as follow:
10 days x 24 Hours x 1 CPU x 1$/CPU/Hour + 20 days x 24 Hours x 2 CPU x 1 CPU x 1$/CPU/Hour = 240$ + 960$ = 1200 $`

Can you demonstrate how it can be calculated with miq-consumption?
How to set ShowbackRate,... and what everything is needed from miq db (Metric, MetricRollups,...)

cc @gtanzillo
@miq-bot assign @sergio-ocon  @aljesusg 

thanks!

**Comment by lpichler** [comment]
@miq-bot add_label question

**Comment by chargio** [comment]
@lpichler Can we close this now?

**Comment by lpichler** [comment]
@chargio,yes

**Comment by ghost** [comment]
Hi @sergio-ocon, it seems like somebody is looking for you regarding chargeback!
