### ISSUE TITLE
performance of  ManageIQ::Consumption::ConsumptionManager.update_events

### ISSUE THREAD

**Issue by lpichler** [ManageIQ/manageiq-consumption#54]
I have 
`
Host.count => 12
VmOrTemplate.count => 1233
Container.count => 924
Metric.count => 93738
...
`

I did the demo step and I ended with 
`ManageIQ::Consumption::ConsumptionManager.update_events`

```
:rows_by_class:
  ManageIQ::Consumption::ShowbackEvent: 1290
  VmOrTemplate: 366
  Metric: 0
  Hardware: 366
  Tag: 414
  Container: 924
  VimPerformanceState: 3144
:total_queries: 11893
:total_rows: 6504
```
I think that 11893 of queries is too much.
Can we reduce it ?
I can provide the db with all data.

@sergio-ocon 
@aljesusg

**Comment by chargio** [comment]
This happens because we need to see if there is a new event every time we do an update, so we need to go through all tables.
IT should be a matter of optimizing this with graph refresh or create an after_create in the models
