### ISSUE TITLE
Showback domain model docs

### ISSUE THREAD

**Issue by lpichler** [ManageIQ/manageiq-consumption#57]
there is ERD diagram:
<img width="1122" alt="screen shot 2017-07-25 at 18 19 31" src="https://user-images.githubusercontent.com/14937244/28582514-f237a07a-7165-11e7-8452-ca2e4cbb7fa3.png">

I know we discussed it but can you please provide some short description for each model - about what they are exactly for?

thanks!

@miq-bot add_label documentation

cc @sergio-ocon @aljesusg

**Comment by aljesusg** [comment]
Yeah, We wanna make some documentation about in a website or google drive. I am in a travel nos but I can Provide you some information now and I'll give you more in few days.

ShowbackUsageType --> Provide all information about whar kind of measure are supported in the chargeback. Where category is the kind of resource(VM, CONTAINER...)  , Measure the type of metric(CPU,memory,storage...) And dimension the operations about (average_cpu, max_cpu...) all of them should be include in showbackevent folder (there is a spec to check It).

ShowbackEvent  --> For each kind of resource will be a object with his metrics,  ShowbackEvent use showbackusagetype and create the data json with all the information about.

Showbackpool --> (bucket) Is the way how we storage the calculations about costs specificated in showbackcharges about a resource. Note : a Pool include 1 or + ShowbackEvent, for example a Pool of a Cluster will include their hosts and vms events.

ShowbackPriceplan --> It's like the actual in chargeback , by default you have an Enterprise plan and its associated with a resource and have the showbackRates for build the report.

ShowbackRate --> Here is the configuration about the chargeback fixed costs, variable costs, steps...like the old chargeback.

Maybe @sergio-ocon  can provide more information this is hard with the mobile ^^. I'll make more documentation @lpichler. Thanks.

**Comment by chargio** [comment]
Showback event: unique per resource (VM, pod, service, etc). Acts as a metrics rollups per resource, getting all the information needed for chargeback. Once the showback event is updated, we don't need to go back to C&U or inventory data.
Showback events are created depending on the inventory, and updated depending on inventory + C&U data.
Events are updated independently of rating, so they should always reflect up to date information.

Showback pool: associated to a resource. It links the events and the resource. A showback pool has all the events associated to a resource in a period. Close but not equal to a bill.

Showback Price Plan: Associated to a resource, it groups all the rates that apply.

Showback rate: A rate is applicable to a single measure from an event. Many rates can be applicable, not only one

**Comment by lpichler** [comment]
thanks! it is helpful and mostly it is clear.
but just one model is not and it `ManageIQ::Consumption::ShowbackCharge`.

there is just one method to find price plan. Can I get more info about this model? What does it model?

**Comment by chargio** [comment]
ShowbackCharge: 
ShowbackEvents are associated to ShowbackPools through ShowbackCharges. That allows us to associate charges independently of any other. As Events can be associated to different pools, we need a means to know the cost associated to the event in the pool (that basically depends on the price plan and the rates that are applicable).
This allows us to get a single event into different pools (i.e. user + group + tenant, or different groups or different tags or whatever), and get a charge associated to it.
For instance, a pod could be associated to a user with a price plan and to a group with a different price plan. Charge would tell us the costs calculated.
Also, having this allows us to know what is the cost so far, even if we don't update charges all the time, if we update it often, we can tell the user what is the cost accrued, without having to calculate it again, and thus being able to use those number in policies, reports, etc.
