### ISSUE TITLE
Needs a better description

### ISSUE THREAD

**Issue by bdunne** [ManageIQ/manageiq-consumption#59]
I followed a link to this repo from ManageIQ/manageiq and did not know what this is.  The descriptions in README.md and https://github.com/miq-consumption/manageiq-consumption/blob/master/manageiq-consumption.gemspec#L14 weren't helpful.  
After browsing the code and talking to others it seems to be related to ManageIQ's Chargeback feature, is that correct?  
If so, can someone please update the description to reflect that?
Is it a replacement for chargeback or enhancements?

**Comment by chargio** [comment]
We are on it!

**Comment by chargio** [comment]
@bdunne Can you please have a look at issue #57. We explain some things there.

**Comment by chargio** [comment]
@bdunne Updated the wiki, please have a look at it and let us know if it is good enough for developers (we need the UI to create user documentation)
