### ISSUE TITLE
[QUESTION] Why is not used MetricRollup ? 

### ISSUE THREAD

**Issue by lpichler** [ManageIQ/manageiq-consumption#70]
I point out
https://github.com/miq-consumption/manageiq-consumption/blob/master/app/models/manageiq/consumption/showback_event.rb#L78
https://github.com/miq-consumption/manageiq-consumption/blob/master/app/models/manageiq/consumption/showback_event.rb#L107

Why here is not used MetricRollup? 

In `MetricRollup`s are roll-up values(so we don't need to calculate it again) and I think that `Metric`s can be purged.(not sure if we can rely on it)

cc @sergio-ocon

**Comment by chargio** [comment]
@aljesusg ?

**Comment by lpichler** [comment]
it should be definitely taken from MetricRollups.
in Metrics we have 20s samples and they are purged and in addition in MetricRollup we have calculated data.

**Comment by aljesusg** [comment]
The point is that we don't if events are gonna be updated by hour (containers) or by day, in the first case maybe the metrics are not aggregated in metric roll up when the event update is triggered. I don't know how exactly is running the metrics_rollups.

Anyway the change is easy 

https://github.com/miq-consumption/manageiq-consumption/blob/master/app/models/manageiq/consumption/showback_event.rb#L88
https://github.com/miq-consumption/manageiq-consumption/blob/master/app/models/manageiq/consumption/showback_event.rb#L118

Change **metrics** by **metric_rollups**, I need to studied how is ManageIq working with this.

**Comment by lpichler** [comment]
Anyway the change should easy, yes and but it is also in specs :) I think that search & replace could solve it.
