### ISSUE TITLE
[QUESTION] ManageIQ::Consumption::ShowbackEvent::[CPU, MEM]

### ISSUE THREAD

**Issue by lpichler** [ManageIQ/manageiq-consumption#74]
for example CPU
```ruby
module ManageIQ::Consumption::ShowbackEvent::CPU
  #
  #  Return the average acumulated with the new one
  #
  def CPU_average(value)
    if @metrics.count>0
      ((value * event_days + @metrics.average(:cpu_usage_rate_average)) / (event_days + 1))
    else
      value
    end
  end

  #
  # Return Number Ocurrences
  #
  def CPU_number(value)
    return value
  end

  #
  #  Return the max number of cpu for object
  #
  def CPU_max_number_of_cpu(value)
    if resource.class.name.ends_with?("Container")
      numcpus = resource.vim_performance_states.last.state_data[:numvcpus]
    else
      numcpus = if resource.methods.include?(:cpu_total_cores) then resource.cpu_total_cores else 0 end
    end
    [value, numcpus].max.to_i
  end
end
```
I have couple questions for this.

I understand that these methods calculating metrics and these are stored to the ShowbackEvent and values stored in the ShowbackEvent are used for rating.

**1. In which units have to be these values related to time base?
For example** (to me it looks like metric value per day)
```ruby
  def CPU_average(value)
    if @metrics.count>0
      ((value * event_days + @metrics.average(:cpu_usage_rate_average)) / (event_days + 1))
    else
      value
    end
  end
```

**1a) should not be average calculated by time as we have similar issue here https://github.com/ManageIQ/manageiq/pull/12582 ?**
**1b) Should not it be in hours ?**
**1c) How I know if these methods represents used or allocated ?**
****
**1d)
Let's assume that Vm comes to the system on Aug 1 and today is Aug 2 and I want to do chargeback on Aug 2** 

- on  Aug 1 is called update_event on the event as it comes to the system. so it has calculated value as zero. 
what start_time and end_time will be set ?

- 1e) where is called update_event again to update values ? after which process ?
- 1f) let's assume that method is called on 2 Aug on end of day (where ? 1e) and lets assume that we have metrics to the 2 Aug.

@metrics are from interval `end_time` to `start_time.end_of_month` so in this case it will take  from Aug 2 to end of Aug.
so I think it will not take into account any metrics ? 

**1g) why when I want to do average only from 1 to 2 Aug(on event) is calculated  average of whole month ?**

**1h)** or maybe you can provide example(only what happess with event not other things) what will explain what should exaclty happen,what time are setup, for example when Vm will comes on 1 Aug at 10:00 and I want to do chargeback on 2 Aug on 17:00.
I mean 
Vm  comes to system after refresh and event is created (when, where ?) and event is updated(when,where ?, by wich process what times will we set up ?) and then what process will updated event on 2.aug (..)? 

**2. How this works ?**
```ruby
  def CPU_number(value)
    return value
  end
```

According to the code the value will be still 0 from generating of events . as I am understanding well.

 @sergio-ocon @aljesusg

**Comment by chargio** [comment]
HI,

There is a PR to add this in showback_events and another to add this in rating. The model added those fields recently.
