### ISSUE TITLE
ordering metrics

### ISSUE THREAD

**Issue by lpichler** [ManageIQ/manageiq-consumption#76]
from `/app/models/manageiq/consumption/showback_event.rb:85`

```ruby
  def update_event
    generate_data unless self.data.present?
    @metrics = if  resource.methods.include?(:metrics) then metrics_time_range(end_time,start_time.end_of_month) else [] end
    self.data.each do |key,dimensions|
      dimensions.keys.each do |dim|
        self.data[key][dim] = self.send("#{key}_#{dim}", data[key][dim].to_d)
      end
    end
    if @metrics.count>0
      self.end_time = @metrics.last.timestamp  # <--- How do we know that last metrics is really the last metric of the interval ?
    end
    collect_tags
  end
```

I think that we should ordering on the query.

**Comment by aljesusg** [comment]
Hi @lpichler Thanks for the issue and sorry but I've been busy this weekend. We are using the metrics method for_time_range. Good point check if we are getting the metrics in order, I thought model return them in order but not...
```ruby
def for_time_range(start_time, end_time)
      if start_time.nil?
        none
      elsif start_time == end_time
        where(:timestamp => start_time)
      elsif end_time.nil?
        where(arel_table[:timestamp].gteq(start_time))
      else
        where(:timestamp => start_time..end_time)
      end
    end
```

Maybe we can do a @metrics.sort_by { |k| k["timestamp"] } or in this case than we only need the timestamp map{|x| x[:timestamp]}.max . What do you think @sergio-ocon =

**Comment by chargio** [comment]
@aljesusg @lpichler Can we use metrics-rollup here? Would we need to have two alternate versions in case metrics-rollups is not working?.

Would it be possible to order it in the DB? 
https://apidock.com/rails/ActiveRecord/QueryMethods/order

It should be faster

**Comment by lpichler** [comment]
@sergio-ocon yes certainly, we should use  `order` in DB. 

I think that if metrics-rollups "don't working" then metric also "don't working", so yes we need to use metric rollups. as it is in https://github.com/miq-consumption/manageiq-consumption/issues/70

**Comment by chargio** [comment]
Do we have an update on this? @lpichler
